#!/bin/sh
#
# Regenerates ../ps3gl_shader_data.h from the Cg sources in this folder.
# NOT part of the normal build: the header is in the tree, so building
# the game needs neither of these tools.
#
# Needs:
#   cgc     NVIDIA Cg Toolkit 3.1, Linux build. On Ubuntu/WSL:
#             sudo apt install nvidia-cg-toolkit
#   cgcomp  PSL1GHT's, only its assembler mode (-a), which doesn't need
#           the Cg library: $PS3DEV/bin/cgcomp
#
# cgc turns Cg into NV40 assembly (profiles vp40 / fp40), cgcomp -a turns
# the assembly into the .vpo/.fpo binaries PSL1GHT loads. Same two steps as
# IoQuake3-PS3's compile_shaders.sh.
#
#   cd src/backends/ps3/gl/shaders && sh build_shaders.sh

set -e

CGC=${CGC:-cgc}
CGCOMP=${CGCOMP:-$PS3DEV/bin/cgcomp}

command -v "$CGC" >/dev/null 2>&1 || { echo "cgc not found (sudo apt install nvidia-cg-toolkit)"; exit 1; }
[ -x "$CGCOMP" ] || { echo "cgcomp not found at $CGCOMP"; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

"$CGC" -quiet -profile vp40 -o "$TMP/q2_vp.asm" q2_vp.vcg
"$CGCOMP" -a -v "$TMP/q2_vp.asm" "$TMP/q2_vp.vpo" >/dev/null

for fp in q2_fp_color q2_fp_modulate q2_fp_replace q2_fp_lightmap q2_fp_lightmap2x q2_fp_lightmap4x q2_fp_present; do
	"$CGC" -quiet -profile fp40 -o "$TMP/$fp.asm" $fp.fcg
	"$CGCOMP" -a -f "$TMP/$fp.asm" "$TMP/$fp.fpo" >/dev/null
done

python3 - "$TMP" <<'PYEOF'
import sys
tmp = sys.argv[1]
progs = ["q2_vp.vpo", "q2_fp_color.fpo", "q2_fp_modulate.fpo", "q2_fp_replace.fpo",
         "q2_fp_lightmap.fpo", "q2_fp_lightmap2x.fpo", "q2_fp_lightmap4x.fpo",
         "q2_fp_present.fpo"]
out = ["/* ps3gl_shader_data.h -- GENERATED by shaders/build_shaders.sh, don't edit.",
       " * Compiled RSX programs (cgc vp40/fp40 + PSL1GHT cgcomp -a) of the Cg",
       " * sources in shaders/. */",
       "",
       "#ifndef PS3GL_SHADER_DATA_H",
       "#define PS3GL_SHADER_DATA_H",
       ""]
for p in progs:
    data = open(tmp + "/" + p, "rb").read()
    name = p.replace(".", "_")
    out.append("static const unsigned char %s[] __attribute__((aligned(16))) = {" % name)
    for i in range(0, len(data), 12):
        out.append("\t" + ", ".join("0x%02x" % b for b in data[i:i+12]) + ",")
    out.append("};")
    out.append("")
out.append("#endif")
open("../ps3gl_shader_data.h", "w").write("\n".join(out) + "\n")
print("wrote ../ps3gl_shader_data.h (%d programs)" % len(progs))
PYEOF
